openapi: 3.0.0
info:
  version: 1.0.0
  title: Backend Documentation API
  description: A simple blog API
  contact:
    name: WONG Hang-chit
    contact: hcwong@vtc.edu.hk
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/license/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:10888/api/v1'
    description: Development Server
tags:
  - name: Users
    description: API enpoints for user management
  - name: Articles
    description: Access and perform CRUD operations on blog entries
paths:
  /articles:
    get:
      tags:
        - Articles
      description:
        Get ALL articles from database
    post:
      tags:
        - Articles
      description:
        Create an article
      requestBody: 
        description: All new article data.
        required: true
        content:
          application/json:
            schema:
              $ref: ./article.json#/definitions/article
  /articles/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Numberic id of the articles (not less than 0)
    get:
      tags:
        - Articles
      description:
        Get article by id.
      responses:
        '200':
          description: View of an article record
        '404':
          description: Article was not found in the DB
    put:
      tags:
        - Articles
      description:
        Update article by ID
      responses:
        '200':
          description: Update of an article record with delegated ID
        '404':
          description: Article was not found in the DB
    delete:
      tags:
        - Articles
      description:
        Delete article by ID
      responses:
        '200':
          description: Delete delegated ID article record
        '404':
          description: Article was not found in the DB